### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by mzafarr** [Lin-jun-xiang/docGPT-streamlit#4]
### Issue you'd like to raise.

Hi there! I wanted to make changes in it with which the uploaded documents stay in the memory and we get an option to later on add more delete from previous documents. How can that be done?
thanks.

**Comment by Lin-jun-xiang** [comment]
@mzafarr 

Are you referring to the scenario where documents uploaded for the first time are stored in memory, and when subsequent documents are uploaded, they are added to the existing memory? This would allow users to reference the content of both the first and second (or more) documents when making inquiries. Is that correct?

**Comment by mzafarr** [comment]
Yes that's correct.

**Comment by Lin-jun-xiang** [comment]
In `docGPT` we just create vector store each time, because of the memory limit just have 1GB in streamlit.


The following code is what you might be interested in. You can refer to the [link](https://github.com/langchain-ai/langchain/discussions/4188) and make modifications to the code; this will meet your requirements.

https://github.com/Lin-jun-xiang/docGPT-langchain/blob/2c46a1bb75df097753d175b46f749c6adabe45b9/docGPT/docGPT.py#L163-L166

**Comment by mzafarr** [comment]
Have you seen any repo that already has this feature? That would be great, because I have to find a solution very urgently

**Comment by Lin-jun-xiang** [comment]
@mzafarr 

I'm sorry. I didn't found any repo that has this feature now.

If I find the feature i will tell you immediately.
